### PR TITLE
Corrected .js files

### PR DESCRIPTION
**Pull request by criadoperez**
Fixed some incorrect texts on .js files

### CODE REVIEW

**Comment by krlosMata** [comment]
hi !!
could you do a rebase with current `develop` branch, since we introduce several changes since then.
Thanks !!

**Comment by krlosMata** [comment]
hi !!
in order to merge your fixes, there are some conflicts xD
could you please rebase your branch with current `develop` so the PR can be merged.
Thanks!

**Comment by criadoperez** [comment]
Fixed the conflicts.

**Review by krlosMata — APPROVED** [review]
:smile_cat:

**Pull request merged**
